# Generated by Django 4.2.10 on 2024-03-12 17:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Activ'), ('0', 'Noactiv')], default='1', max_length=2)),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Compleks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Activ'), ('0', 'Noactiv')], default='1', max_length=2)),
                ('schema_net', models.ImageField(upload_to='ticket/images')),
                ('documents', models.ImageField(upload_to='ticket/images')),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='Partnyor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=200)),
                ('login', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=10)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Activ'), ('0', 'Noactiv')], default='1', max_length=2)),
                ('image', models.ImageField(upload_to='ticket/images')),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.CharField(choices=[('1', 'Activ'), ('0', 'Noactiv')], default='1', max_length=2),
        ),
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('note', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('1', 'Activ'), ('0', 'Noactiv')], default='1', max_length=2)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='ticket/images')),
                ('endDate', models.DateTimeField()),
                ('update_Time', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.company')),
                ('compleks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.compleks')),
                ('partnyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.partnyor')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
    ]
