# Generated by Django 4.2.10 on 2024-03-12 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0002_company_compleks_partnyor_alter_problem_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compleks',
            name='documents',
            field=models.FileField(upload_to='ticket/images'),
        ),
        migrations.CreateModel(
            name='Navbatchilik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kun', models.CharField(max_length=200)),
                ('oy', models.CharField(max_length=200)),
                ('yil', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Activ'), ('0', 'Noactiv')], default='1', max_length=2)),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.tickets')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('info', models.CharField(max_length=220)),
                ('date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('1', 'Activ'), ('0', 'Noactiv')], default='1', max_length=2)),
                ('file', models.FileField(upload_to='ticket/images')),
                ('read', models.CharField(max_length=200)),
                ('toDate', models.DateTimeField(auto_now=True)),
                ('endDate', models.DateTimeField()),
                ('creatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
