# Generated by Django 4.2.10 on 2024-03-18 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_alter_compleks_documents_navbatchilik_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='partnyor',
            name='companyId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partnyor',
            name='contacts',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
