# Generated by Django 4.2.10 on 2024-06-19 11:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0005_students_partnyor_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('description', models.TextField()),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('duty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_duty', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tblevents',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('note', models.CharField(max_length=250)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('file', models.ImageField(null=True, upload_to='ticket/images')),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('file', models.FileField(upload_to='ticket/images')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorTodo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='navbatchilik',
            name='creatorId',
        ),
        migrations.RemoveField(
            model_name='navbatchilik',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Students',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='company',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='compleks',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='partnyor',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='problem',
        ),
        migrations.RemoveField(
            model_name='tickets',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-createDate']},
        ),
        migrations.AlterModelOptions(
            name='partnyor',
            options={},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='compleks',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='compleks',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='partnyor',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='partnyor',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='problem',
            name='created',
        ),
        migrations.AddField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='problem',
            name='createDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compleks',
            name='documents',
            field=models.ImageField(upload_to='ticket/images'),
        ),
        migrations.AlterField(
            model_name='compleks',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='companyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='ticket.company'),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='image',
            field=models.ImageField(blank=True, upload_to='ticket/images'),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='Navbatchilik',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
        migrations.AddField(
            model_name='todo',
            name='compleks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.compleks'),
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTodo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ticket',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.company'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='compleks',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.compleks'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='partnyor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.partnyor'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.problem'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
