# Generated by Django 4.2.10 on 2024-06-20 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0006_duty_events_ticket_todo_userprofile_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='duty',
            options={'ordering': ['-start']},
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bio',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.FileField(default=1, upload_to='ticket/images'),
            preserve_default=False,
        ),
    ]
