# Generated by Django 4.2.10 on 2024-05-14 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0007_datapoint_delete_students'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPoint',
        ),
        migrations.RemoveField(
            model_name='navbatchilik',
            name='ticket',
        ),
        migrations.DeleteModel(
            name='Tickets',
        ),
    ]
