# Generated by Django 4.2.10 on 2024-05-14 17:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0008_delete_datapoint_remove_navbatchilik_ticket_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='education',
            options={'ordering': ['-createDate']},
        ),
        migrations.AlterModelOptions(
            name='navbatchilik',
            options={'ordering': ['-createDate']},
        ),
        migrations.AlterModelOptions(
            name='partnyor',
            options={'ordering': ['-createDate']},
        ),
        migrations.RenameField(
            model_name='company',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='company',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='compleks',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='compleks',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='education',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='navbatchilik',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='navbatchilik',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='partnyor',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='partnyor',
            old_name='created',
            new_name='createDate',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='creatorId',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='problem',
            old_name='created',
            new_name='createDate',
        ),
        migrations.AddField(
            model_name='navbatchilik',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='company',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='compleks',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='navbatchilik',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='problem',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('note', models.CharField(max_length=250)),
                ('status', models.BooleanField(default=False)),
                ('createDate', models.DateTimeField(auto_now_add=True)),
                ('file', models.ImageField(upload_to='ticket/images')),
                ('endDate', models.DateTimeField()),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.company')),
                ('compleks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.compleks')),
                ('partnyor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.partnyor')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-createDate'],
            },
        ),
        migrations.AddField(
            model_name='navbatchilik',
            name='ticket',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticket.ticket'),
            preserve_default=False,
        ),
    ]
