# Generated by Django 4.2.10 on 2024-06-26 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0009_loginhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compleks',
            name='documents',
            field=models.ImageField(blank=True, default='ticket/images/1.jpg', null=True, upload_to='ticket/images'),
        ),
        migrations.AlterField(
            model_name='compleks',
            name='schema_net',
            field=models.ImageField(blank=True, default='ticket/images/1.jpg', null=True, upload_to='ticket/images'),
        ),
    ]
