# Generated by Django 4.2.10 on 2024-05-20 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0009_alter_education_options_alter_navbatchilik_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Navbatchilik',
            new_name='Duty',
        ),
        migrations.AlterModelOptions(
            name='partnyor',
            options={},
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='age',
            field=models.IntegerField(),
        ),
    ]
