# Generated by Django 4.2.10 on 2024-05-21 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0010_rename_navbatchilik_duty_alter_partnyor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='duty',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_duty', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
