# Generated by Django 4.2.10 on 2024-07-01 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0011_events_author_events_color_events_createdate_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table='events',
        ),
    ]
