# Generated by Django 4.2.10 on 2024-05-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
