# Generated by Django 4.2.10 on 2024-07-01 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0012_alter_events_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='events',
            table=None,
        ),
    ]
