# Generated by Django 4.2.10 on 2024-05-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0013_alter_events_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
