# Generated by Django 4.2.10 on 2024-06-01 06:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0014_alter_events_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compleks',
            name='documents',
            field=models.ImageField(upload_to='ticket/images'),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='companyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company', to='ticket.company'),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='image',
            field=models.ImageField(blank=True, upload_to='ticket/images'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
