# Generated by Django 4.2.10 on 2024-07-01 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0014_alter_events_options_alter_events_createdate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='yillar',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Eventlar',
        ),
    ]
