# Generated by Django 4.2.10 on 2024-06-01 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_alter_compleks_documents_alter_partnyor_companyid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='endDate',
            field=models.DateTimeField(null=True),
        ),
    ]
