# Generated by Django 4.2.10 on 2024-07-02 04:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0015_yillar_delete_eventlar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='yillar',
        ),
    ]
