# Generated by Django 4.2.10 on 2024-07-02 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0016_delete_yillar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='status',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
