# Generated by Django 4.2.10 on 2024-07-09 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0017_alter_events_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnyor',
            name='contacts',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='partnyor',
            name='login',
            field=models.CharField(max_length=15),
        ),
    ]
