# Generated by Django 4.2.10 on 2024-06-03 13:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0018_ticket_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_teacher', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='education',
            name='date',
            field=models.DateTimeField(blank=True),
        ),
    ]
