# Generated by Django 4.2.10 on 2024-07-09 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0018_alter_partnyor_contacts_alter_partnyor_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='read',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
