# Generated by Django 4.2.13 on 2024-06-04 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0019_education_teacher_alter_education_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='duty',
            name='date_duty',
            field=models.DateField(null=True),
        ),
    ]
