# Generated by Django 4.2.10 on 2024-07-09 09:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0019_alter_education_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='user',
        ),
        migrations.AddField(
            model_name='ticket',
            name='user',
            field=models.ManyToManyField(related_name='tickets', to=settings.AUTH_USER_MODEL),
        ),
    ]
