# Generated by Django 4.2.13 on 2024-06-04 11:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0020_duty_date_duty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='kun',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='oy',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='yil',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='endDate',
        ),
        migrations.AddField(
            model_name='duty',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='duty',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='start',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='duty',
            name='date_duty',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorTodo', to=settings.AUTH_USER_MODEL)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.company')),
                ('compleks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticket.compleks')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userTodo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbltodo',
            },
        ),
    ]
