# Generated by Django 4.2.13 on 2024-06-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0021_remove_duty_kun_remove_duty_oy_remove_duty_yil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='file',
            field=models.FileField(default=1, upload_to='ticket/images'),
            preserve_default=False,
        ),
    ]
