# Generated by Django 4.2.10 on 2024-07-10 10:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0021_alter_ticket_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='user',
        ),
        migrations.AddField(
            model_name='todo',
            name='user',
            field=models.ManyToManyField(related_name='todo', to=settings.AUTH_USER_MODEL),
        ),
    ]
