# Generated by Django 4.2.10 on 2024-07-10 10:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ticket', '0022_remove_todo_user_todo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='read',
        ),
        migrations.AddField(
            model_name='education',
            name='read',
            field=models.ManyToManyField(related_name='read_educations', to=settings.AUTH_USER_MODEL),
        ),
    ]
