# Generated by Django 4.2.13 on 2024-06-05 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0022_todo_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todo',
            options={'ordering': ['-start']},
        ),
        migrations.AlterModelTable(
            name='todo',
            table=None,
        ),
    ]
