# Generated by Django 4.2.14 on 2024-09-04 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_readeducationlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
    ]
