# Generated by Django 5.0.6 on 2024-06-15 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0024_alter_todo_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='duty',
            name='date_duty',
        ),
        migrations.RemoveField(
            model_name='duty',
            name='ticketId',
        ),
    ]
