# Generated by Django 5.0.6 on 2024-06-15 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0025_remove_duty_date_duty_remove_duty_ticketid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='company',
        ),
        migrations.AddField(
            model_name='duty',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='color',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='file',
            field=models.ImageField(null=True, upload_to='ticket/images'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='partnyor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.partnyor'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='problem',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ticket.problem'),
        ),
    ]
